language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly
install: composer install
before_script:
  - cp src/config.example.php src/config.php
  - cp propel/propel.example.json propel/propel.json
  - composer propel:config
script: phpunit -c tests/phpunit.xml
