language: php
php:
  - '7.0'
  - '7.1'
install: composer install
before_script:
  - cp src/config.example.php src/config.php
  - cp propel/propel.example.json propel/propel.json
  - composer propel:config
  - composer propel:model
  - composer update
script: phpunit -c tests/phpunit.xml
