#!/bin/sh
set -e
echo ""
echo "Changing to test database..."
echo ""
initial_dir=`pwd`
propel_dir=../../propel
test_propel_config_dir_from_propel_dir=../tools/tests/
propel_bin_from_propel_dir=../vendor/bin/propel

cd $propel_dir
# Generate connection file (linking to the TestDB)
$propel_bin_from_propel_dir config:convert --config-dir=$test_propel_config_dir_from_propel_dir
# Rebuild Classes, not really necessary but nice to make sure its all working as intended and prevent conflicts with older autogenerated files
$propel_bin_from_propel_dir sql:build --overwrite --config-dir=$test_propel_config_dir_from_propel_dir
$propel_bin_from_propel_dir model:build
# Seeds DB
$propel_bin_from_propel_dir sql:insert --config-dir=$test_propel_config_dir_from_propel_dir
echo ""
echo "You are now in the TESTDB. Have fun!"
echo ""
